"""db initialize

Revision ID: 0d6b72a61265
Revises: 
Create Date: 2023-04-28 09:32:28.625591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6b72a61265'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beer', sa.Column('style', sa.String(), nullable=True))
    op.create_index(op.f('ix_beer_style'), 'beer', ['style'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beer_style'), table_name='beer')
    op.drop_column('beer', 'style')
    # ### end Alembic commands ###
