"""add is_active to hops

Revision ID: 507faa167c4d
Revises: 596994a924da
Create Date: 2023-04-28 15:03:07.417936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507faa167c4d'
down_revision = '596994a924da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hops', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hops', 'is_active')
    # ### end Alembic commands ###
