"""hops and relation

Revision ID: 596994a924da
Revises: 0d6b72a61265
Create Date: 2023-04-28 13:59:08.880484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596994a924da'
down_revision = '0d6b72a61265'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hops_description'), 'hops', ['description'], unique=False)
    op.create_index(op.f('ix_hops_id'), 'hops', ['id'], unique=False)
    op.create_index(op.f('ix_hops_name'), 'hops', ['name'], unique=True)
    op.create_table('relation_hops_beer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.Column('hops_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beer.id'], ),
    sa.ForeignKeyConstraint(['hops_id'], ['hops.id'], ),
    sa.PrimaryKeyConstraint('id', 'beer_id', 'hops_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_hops_beer')
    op.drop_index(op.f('ix_hops_name'), table_name='hops')
    op.drop_index(op.f('ix_hops_id'), table_name='hops')
    op.drop_index(op.f('ix_hops_description'), table_name='hops')
    op.drop_table('hops')
    # ### end Alembic commands ###
